hw04 done
dasmoro/otus_golang_homework pull request #4
Opened 2020-12-28 17:26 UTC by dasmoro

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-01-02 20:37 UTC, balabanovds requested changes
Хорошая работа.

Есть несколько замечания по стилю, также вопрос в тестах - непонятно зачем там кусок кода.
Также не увидел теста на логику выталкивания из кэша редко используемых элементов.

Пока возвращаю на доработку.

Успехов!

https://otus.ru/teacher-lk/homework/146868/9018/

2021-01-02 20:37 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	GetCacheKeys() []interface{}
какой смысл в этом методе? он нигде не используется

2021-01-02 20:37 UTC, balabanovds commented on hw04_lru_cache/cache.go
>  func NewCache(capacity int) Cache {
объявление контруктора обычно лучше воспринимается если его размещать сразу после объявления структуры

2021-01-02 20:37 UTC, balabanovds commented on hw04_lru_cache/list_test.go
> +			elems := make([]int, 0, l.Len())
можете пояснить для чего так сделано?

2021-01-02 20:37 UTC, balabanovds commented on hw04_lru_cache/list.go
> +		l.head.Next = i
у Вас же есть метод PushFront

2021-01-02 20:37 UTC, balabanovds commented on hw04_lru_cache/cache_test.go
> +// func TestCacheMultithreading(t *testing.T) {
закомментированный код в репе выглядит как мусор

2021-01-08 17:08 UTC, dasmoro commented on hw04_lru_cache/cache.go
> +	GetCacheKeys() []interface{}
Использовал его для дебага. Сейчас убрал

2021-01-08 17:08 UTC, dasmoro commented on hw04_lru_cache/cache.go
>  func NewCache(capacity int) Cache {
Переместил

2021-01-08 17:09 UTC, dasmoro commented on hw04_lru_cache/list_test.go
> +			elems := make([]int, 0, l.Len())
Здесь проверятся правильно ли работает метод при при перемещении в начало головы и хвоста списка, так как это исключительные ситуации метода

2021-01-08 17:11 UTC, dasmoro commented on hw04_lru_cache/list.go
> +		l.head.Next = i
Если использовать PushFront то будет происходить дополнительное выделение памяти под новое значение, а так как мы можем хранить в элементе списка все что угодно, то это может быть более трудоемкая задача нежели чем перелинковка существующего элемента, как сделано сейчас

2021-01-08 17:11 UTC, dasmoro commented on hw04_lru_cache/cache_test.go
> +// func TestCacheMultithreading(t *testing.T) {
Убрал

2021-01-08 19:52 UTC, balabanovds commented on hw04_lru_cache/list_test.go
> +			elems := make([]int, 0, l.Len())
Не совсем понятно.
У Вас создается слайс elems, который виден только с 48 по 53 строчку.
В данной области видимости Вы просто пробегаетесь по всему листу и закидываете значения в слайс. 
Никаких проверок не видно..
Выглядит как лишняя работа.

2021-01-08 19:57 UTC, balabanovds approved these changes, later dismissed
Спасибо за пояснения.

По тесту прошу пояснить, отписался в комментарии к предыдущему ревью (пока -1 балл).
Нет теста на логику выталкивания редкоиспользуемых элементов (это -2 балла)

Пока оценка 7/10

2021-01-09 08:37 UTC, balabanovds commented
> Спасибо за пояснения.
> 
> По тесту прошу пояснить, отписался в комментарии к предыдущему ревью (пока -1 балл).
> Нет теста на логику выталкивания редкоиспользуемых элементов (это -2 балла)
> 
> Пока оценка 7/10

Все увидел - два теста объединили в один. До [строки](https://github.com/dasmoro/otus_golang_homework/blob/73b5579b05b5dafb3289dea4afb38f8b6a4da491/hw04_lru_cache/cache_test.go#L60) идет первый тест на выталкивание из-за размера очереди, потом на редкоиспользуемые элементы.. Наверное на будущее нужно более явно как-то разделять тесты..

9/10

2021-01-10 05:13 UTC, balabanovds approved these changes
Отлично!
Теперь применение `elems` очевидно

2021-01-16 21:35 UTC, merged